### ISSUE TITLE
可否直接调用x265进行编码操作？

### ISSUE THREAD

**Issue by ghost** [JasinChen/x265-command-editor#1]
仅仅是生成命令行的话感觉还是不大方便，要是能调完参数直接开始编码输出就好了，而且可以再加上批量输入输出

**Comment by thunderiser** [comment]
或者再加上批量输入输出就完美了

**Comment by JasinChen** [comment]
在程序内调用命令行没办法实时显示输出信息，只能默默等他编码完。
批量输出已添加

**Comment by JasinChen** [comment]
> 仅仅是生成命令行的话感觉还是不大方便，要是能调完参数直接开始编码输出就好了，而且可以再加上批量输入输出

在程序内调用命令行没办法实时显示输出信息，只能默默等他编码完。
批量输出已添加

**Comment by ghost** [comment]
> > 仅仅是生成命令行的话感觉还是不大方便，要是能调完参数直接开始编码输出就好了，而且可以再加上批量输入输出
> 
> 在程序内调用命令行没办法实时显示输出信息，只能默默等他编码完。
> 批量输出已添加

最新版导入视频的时候会闪退

**Comment by JasinChen** [comment]
> > > 仅仅是生成命令行的话感觉还是不大方便，要是能调完参数直接开始编码输出就好了，而且可以再加上批量输入输出
> > 
> > 
> > 在程序内调用命令行没办法实时显示输出信息，只能默默等他编码完。
> > 批量输出已添加
> 
> 最新版导入视频的时候会闪退

能发一下崩溃的视频的信息吗，方便的话qq联系
