### ISSUE TITLE
打开“导入视频”对话框片刻后程序卡住

### ISSUE THREAD

**Issue by Xueipyet** [JasinChen/x265-command-editor#2]
使用的是1.1版本下的“x265.command.editor-full.7z“。在程序”关于“界面，日期显示1-29，版本显示1.0

**Comment by JasinChen** [comment]
你好，可能是弹出窗口的问题，请确认ffprobe可用。
PS.
1.导入视频是用于制作vpy文件或avs文件，若无此用途可无需导入
2.因频繁更新，“关于“界面有时更新延后，请先尝试最新版本
