### ISSUE TITLE
希望可以增加读源滤镜，像LASMAS和DGNV

### ISSUE THREAD

**Issue by Murphy92** [JasinChen/x265-command-editor#4]
希望可以增加读源滤镜，像LASMAS和DGNV，另外可以有个粘贴x265代码进去，直接识别就好了

**Comment by JasinChen** [comment]
> 希望可以增加读源滤镜，像LASMAS和DGNV，另外可以有个粘贴x265代码进去，直接识别就好了

lasmas直接pull下来就有自带，粘贴x265代码功能已加入，dgnv暂不支持
