### ISSUE TITLE
release打包文件巨大

### ISSUE THREAD

**Issue by Purple-CSGO** [JasinChen/x265-command-editor#5]
老哥我发现你发布的文件文件巨大，但其实`.git`文件夹占了600MB，纯属浪费空间了，去掉之后最终打包的文件会小很多

**Comment by JasinChen** [comment]
> 老哥我发现你发布的文件文件巨大，但其实`.git`文件夹占了600MB，纯属浪费空间了，去掉之后最终打包的文件会小很多

忘记删掉他了，过几天重发
